# Generated by Django 3.2.3 on 2021-06-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_name',
            new_name='name',
        ),
    ]
